### ISSUE TITLE
Back-end

### ISSUE THREAD

**Issue by guilhermescherer** [guilhermescherer/product-catalog#6]
A estrutura inicial da API está pronta, o que preciso fazer agora é:
- ~Implementar autorização na API como Resource Server e `keycloak` como Authorization Server~
- ~Verificar com @guilherme-carmo se é necessário mais alguma entidade, como por exemplo, funcionário, venda, etc.~
- ~Testes unitários~
- ~Testes de integração~
- ~Implementar Swagger~
- ~Implementar paginação~
- ~Implementar filtros de acordo com `ProductForm` recebido~

**Comment by guilherme-carmo** [comment]
I guess that, what we want here, is keep it simple
so I think that work only with products is good enough
